import { evolutionRules } from '../data/evolution.js';
export const defaultTickConfig = { hungerEvery: 4, tiredEvery: 5, ageEvery: 12, travelEvery: 10 };
export function createCreature(generation=1, species='baby') { return { species, generation, ageHours:0, weight:5, hunger:0, tiredness:0, sick:false, injuries:0, boost:0, training:0, careMistakes:0, battles:0, victories:0, alive:true, lightsOn:true, dirty:false, evolutionTimer:0 }; }
export function createGame() { return { schemaVersion:1, tickMs:1000, elapsedTicks:0, creature:createCreature(), inventory:{meat:5,protein:2,medicine:2,bandage:2,travel_ration:2}, memorial:[], city:{unlocked:{shop:false,clinic:false,storage:false},npcs:[]}, island:{travelPoints:0,encounterIndex:0,bossesDefeated:[]}, debug:true }; }
export function clamp(n,min,max){return Math.max(min,Math.min(max,n));}
export function tick(state, cfg=defaultTickConfig) { const s=structuredClone(state); if(!s.creature.alive) return s; s.elapsedTicks++; const c=s.creature; if(s.elapsedTicks%cfg.ageEvery===0)c.ageHours++; if(s.elapsedTicks%cfg.hungerEvery===0)c.hunger=clamp(c.hunger+1,0,10); if(s.elapsedTicks%cfg.tiredEvery===0)c.tiredness=clamp(c.tiredness+1,0,10); if(s.elapsedTicks%cfg.travelEvery===0)s.island.travelPoints++; if(c.hunger>=10||c.tiredness>=10)c.careMistakes++; if(c.careMistakes>12||c.injuries>4) kill(s, c.injuries>4?'heridas':'errores de cuidado'); evolve(s); return s; }
export function evolve(s){ const c=s.creature; const rule=evolutionRules.find(r=>r.from===c.species&&c.ageHours>=r.minAgeHours&&(r.maxCareMistakes===undefined||c.careMistakes<=r.maxCareMistakes)&&(r.minTraining===undefined||c.training>=r.minTraining)&&(r.minVictories===undefined||c.victories>=r.minVictories)); if(rule){ c.species=rule.to; c.evolutionTimer=0; c.weight+=3; } else c.evolutionTimer++; }
export function kill(s, reason){ const c=s.creature; if(!c.alive)return; c.alive=false; s.memorial.push({generation:c.generation,species:c.species,ageHours:c.ageHours,victories:c.victories,reason,diedAt:new Date().toISOString()}); }
export function newGeneration(s){ const next=createCreature(s.creature.generation+1); s.creature=next; s.island.activeAreaId=undefined; s.island.encounterIndex=0; return s; }
export function feed(s,item='meat'){ const c=s.creature; if((s.inventory[item]??0)<=0||!c.alive)return s; s.inventory[item]--; if(item==='meat'){c.hunger=clamp(c.hunger-3,0,10);c.weight++;} if(item==='protein'){c.boost=clamp(c.boost+2,0,8);c.tiredness=clamp(c.tiredness+2,0,10);c.weight++;} return s; }
export function train(s){ const c=s.creature;if(!c.alive)return s; c.training++; c.boost=clamp(c.boost+1,0,8); c.tiredness=clamp(c.tiredness+2,0,10); c.hunger=clamp(c.hunger+1,0,10); return s; }
export function cure(s){ const c=s.creature;if((s.inventory.medicine??0)>0&&c.sick){s.inventory.medicine--;c.sick=false;} else if((s.inventory.bandage??0)>0&&c.injuries>0){s.inventory.bandage--;c.injuries--;} return s; }
export function clean(s){s.creature.dirty=false;return s;}
export function toggleLight(s){s.creature.lightsOn=!s.creature.lightsOn;return s;}
