import { loadGame, saveGame, exportGame, importGame } from './storage/save.js';
import { tick, feed, train, cure, clean, toggleLight, newGeneration } from './core/game.js';
import { battle } from './core/battle.js';
import { areas } from './data/areas.js';
import { drawCreature, view } from './ui/render.js';
let state=loadGame(); let frame=0; let flash=false; const app=document.querySelector('#app');
function commit(next=state){ state=next; saveGame(state); render(); }
function islandBattle(){ const area=areas.find(a=>a.id===state.island.activeAreaId); if(!area)return alert('Elige un area.'); const enc=area.encounters[state.island.encounterIndex]; const r=battle(state.creature.species, enc.species, state.creature.boost, enc.boost); state.creature.battles++; flash=true; setTimeout(()=>{flash=false;render();},350); if(r.victory){ state.creature.victories++; state.island.encounterIndex++; if(enc.recruitNpc&&!state.city.npcs.includes(enc.recruitNpc))state.city.npcs.push(enc.recruitNpc); if(enc.boss){ state.island.bossesDefeated.push(enc.id); if(enc.unlocksBuilding)state.city.unlocked[enc.unlocksBuilding]=true; state.island.activeAreaId=undefined; state.island.encounterIndex=0; alert(`Victoria boss (${Math.round(r.chance*100)}%). Edificio desbloqueado.`); } } else { state.creature.injuries += Math.random()<0.5?1:0; state.island.activeAreaId=undefined; state.island.encounterIndex=0; alert(`Derrota (${Math.round(r.chance*100)}%). Expedicion reiniciada.`); } commit(); }
function render(){ app.innerHTML=view(state); const canvas=document.querySelector('#screen'); drawCreature(canvas,state,frame,flash); app.onclick=(e)=>{ const t=e.target; const action=t.dataset.action; const areaId=t.dataset.area; if(areaId){ const a=areas.find(x=>x.id===areaId); if(state.island.travelPoints>=a.travelCost){state.island.travelPoints-=a.travelCost; state.island.activeAreaId=a.id; state.island.encounterIndex=0; commit();} return; } if(!action)return; if(action==='feed')commit(feed(state,'meat')); if(action==='protein')commit(feed(state,'protein')); if(action==='train')commit(train(state)); if(action==='cure')commit(cure(state)); if(action==='light')commit(toggleLight(state)); if(action==='clean')commit(clean(state)); if(action==='newgen')commit(newGeneration(state)); if(action==='battle')islandBattle(); if(action==='retreat'){state.island.activeAreaId=undefined;state.island.encounterIndex=0;commit();} if(action==='export'){document.querySelector('#savebox').value=exportGame(state);} if(action==='import'){try{commit(importGame(document.querySelector('#savebox').value));}catch(err){alert(String(err));}} }; }
setInterval(()=>{ frame++; commit(tick(state)); }, state.tickMs);
render();
